---
openapi: 3.0.0
info:
  title: My Blog Api
  description: "This is the first formal api project. This is simple blog application. where anyone can create a new account, login to there system and create articels that will be visible publicy."
  contact:
    name: Nirob
    url: https://nirob.com
    email: nirob@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/nirob-organization/my-blog-api/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:5000/api/v1
  description: dev
tags:
- name: Auth
  description: authentication Endpoints
- name: Article
  description: Article Endpints
- name: Comment
  description: Comment Endpoints
- name: User
  description: User Endpoints
paths:
  /auth/signup:
    post:
      tags:
      - Auth
      description: create new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_signup_body'
      responses:
        "201":
          description: signup successfull
          content:
            application:
              schema:
                $ref: '#/components/schemas/inline_response_201'
components:
  schemas:
    auth_signup_body:
      required:
      - email
      - name
      - password
      type: object
      properties:
        name:
          type: string
          example: Nirob Hasan
        email:
          type: string
          format: email
          example: nirob@gmail.com
        password:
          type: string
          format: password
          example: pass123
    inline_response_201:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 201
        message:
          type: string
          example: singup successfull
        data:
          type: object
          properties:
            access_token:
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
